### ISSUE TITLE
Ich will Tags bei den Karteikarten :)

### ISSUE THREAD

**Issue by NoWo2000** [piuswalter/StudyOffline#24]
Einmal bitte Tags wie bei StudySmarter einfügen.

**Comment by piuswalter** [comment]
Hello @NoWo2000,
we implemented subject tags to StudyOffline but there are some other things to do before we can release a new version including the functionality of tags. At the moment you can try the tags while using the `development` branch. I will inform you as soon as the new version is released.

**Comment by piuswalter** [comment]
Hello @NoWo2000,
in [StudyOffline v1.2.0](https://github.com/piuswalter/StudyOffline/releases/tag/v1.2.0) you can now filter flashcards by tags. Also the Docker container is now available for use. If you have any further questions, feel free to contact us again.
